"""Initial schema with 5 core tables

Revision ID: 6f06f1cbe0c7
Revises: 
Create Date: 2026-02-04 19:07:51.838839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f06f1cbe0c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bse_code', sa.String(length=10), nullable=True),
    sa.Column('nse_symbol', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('market_cap_cr', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('is_nifty_50', sa.Boolean(), nullable=False),
    sa.Column('is_nifty_500', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index('idx_company_nifty500', 'companies', ['is_nifty_500'], unique=False)
    op.create_index('idx_company_search', 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_bse_code'), 'companies', ['bse_code'], unique=False)
    op.create_index(op.f('ix_companies_is_nifty_500'), 'companies', ['is_nifty_500'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_nse_symbol'), 'companies', ['nse_symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'PREMIUM', name='subscriptiontier'), nullable=False),
    sa.Column('subscription_active', sa.Boolean(), nullable=False),
    sa.Column('reports_used_this_month', sa.Integer(), nullable=False),
    sa.Column('reports_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('annual_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('pages_count', sa.Integer(), nullable=True),
    sa.Column('pdf_hash', sa.String(length=64), nullable=True),
    sa.Column('is_processed', sa.String(length=20), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ar_company_year', 'annual_reports', ['company_id', 'fiscal_year'], unique=False)
    op.create_index('idx_ar_fiscal_year', 'annual_reports', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_annual_reports_company_id'), 'annual_reports', ['company_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flags_triggered_count', sa.Integer(), nullable=False),
    sa.Column('flags_critical_count', sa.Integer(), nullable=False),
    sa.Column('flags_high_count', sa.Integer(), nullable=False),
    sa.Column('flags_medium_count', sa.Integer(), nullable=False),
    sa.Column('flags_low_count', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('key_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_version', sa.String(length=20), nullable=False),
    sa.Column('processing_time_seconds', sa.Integer(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['annual_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_report', 'analysis_results', ['report_id'], unique=False)
    op.create_index('idx_analysis_risk_score', 'analysis_results', ['risk_score'], unique=False)
    op.create_index(op.f('ix_analysis_results_report_id'), 'analysis_results', ['report_id'], unique=False)
    op.create_table('red_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('flag_number', sa.Integer(), nullable=False),
    sa.Column('flag_name', sa.String(length=255), nullable=False),
    sa.Column('flag_description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('AUDITOR', 'CASH_FLOW', 'RELATED_PARTY', 'PROMOTER', 'GOVERNANCE', 'BALANCE_SHEET', 'REVENUE', 'TEXTUAL', name='flagcategory'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='flagseverity'), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('page_references', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flag_analysis_triggered', 'red_flags', ['analysis_id', 'is_triggered'], unique=False)
    op.create_index('idx_flag_category_severity', 'red_flags', ['category', 'severity'], unique=False)
    op.create_index('idx_flag_number', 'red_flags', ['flag_number'], unique=False)
    op.create_index(op.f('ix_red_flags_analysis_id'), 'red_flags', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_red_flags_category'), 'red_flags', ['category'], unique=False)
    op.create_index(op.f('ix_red_flags_is_triggered'), 'red_flags', ['is_triggered'], unique=False)
    op.create_index(op.f('ix_red_flags_severity'), 'red_flags', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_red_flags_severity'), table_name='red_flags')
    op.drop_index(op.f('ix_red_flags_is_triggered'), table_name='red_flags')
    op.drop_index(op.f('ix_red_flags_category'), table_name='red_flags')
    op.drop_index(op.f('ix_red_flags_analysis_id'), table_name='red_flags')
    op.drop_index('idx_flag_number', table_name='red_flags')
    op.drop_index('idx_flag_category_severity', table_name='red_flags')
    op.drop_index('idx_flag_analysis_triggered', table_name='red_flags')
    op.drop_table('red_flags')
    op.drop_index(op.f('ix_analysis_results_report_id'), table_name='analysis_results')
    op.drop_index('idx_analysis_risk_score', table_name='analysis_results')
    op.drop_index('idx_analysis_report', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_annual_reports_company_id'), table_name='annual_reports')
    op.drop_index('idx_ar_fiscal_year', table_name='annual_reports')
    op.drop_index('idx_ar_company_year', table_name='annual_reports')
    op.drop_table('annual_reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_nse_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_nifty_500'), table_name='companies')
    op.drop_index(op.f('ix_companies_bse_code'), table_name='companies')
    op.drop_index('idx_company_search', table_name='companies')
    op.drop_index('idx_company_nifty500', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
